run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert

linters-settings:
  misspell:
    ignore-words:
      - doub
  errcheck:
    exclude-functions:
      - (*database/sql.Tx).Rollback
      - (*database/sql.DB).Close
      - (*database/sql.Rows).Close
      - os.Chdir

issues:
  exclude-dirs:
    - docs
