# Code generated by dbtools generate. DO NOT EDIT.
# Source target: test-target @ 2026-08-22T04:00:00Z

from __future__ import annotations
from datetime import datetime
from decimal import Decimal
from typing import Optional

from pydantic import BaseModel, Field


class Customers(BaseModel):
    """public.customers"""

    customerNumber: int = Field(alias="customerNumber")
    customerName: str = Field(alias="customerName")
    contactLastName: str = Field(alias="contactLastName")
    contactFirstName: str = Field(alias="contactFirstName")
    phone: str = Field(alias="phone")
    addressLine1: str = Field(alias="addressLine1")
    addressLine2: Optional[str] = Field(alias="addressLine2")
    city: str = Field(alias="city")
    state: Optional[str] = Field(alias="state")
    postalCode: Optional[str] = Field(alias="postalCode")
    country: str = Field(alias="country")
    salesRepEmployeeNumber: Optional[int] = Field(alias="salesRepEmployeeNumber")
    creditLimit: Optional[Decimal] = Field(alias="creditLimit")


class Employees(BaseModel):
    """public.employees"""

    employeeNumber: int = Field(alias="employeeNumber")
    lastName: str = Field(alias="lastName")
    firstName: str = Field(alias="firstName")
    extension: str = Field(alias="extension")
    email: str = Field(alias="email")
    officeCode: str = Field(alias="officeCode")
    reportsTo: Optional[int] = Field(alias="reportsTo")
    jobTitle: str = Field(alias="jobTitle")


class Offices(BaseModel):
    """public.offices"""

    officeCode: str = Field(alias="officeCode")
    city: str = Field(alias="city")
    phone: str = Field(alias="phone")
    addressLine1: str = Field(alias="addressLine1")
    addressLine2: Optional[str] = Field(alias="addressLine2")
    state: Optional[str] = Field(alias="state")
    country: str = Field(alias="country")
    postalCode: str = Field(alias="postalCode")
    territory: str = Field(alias="territory")


class Orderdetails(BaseModel):
    """public.orderdetails"""

    orderNumber: int = Field(alias="orderNumber")
    productCode: str = Field(alias="productCode")
    quantityOrdered: int = Field(alias="quantityOrdered")
    priceEach: Decimal = Field(alias="priceEach")
    orderLineNumber: int = Field(alias="orderLineNumber")


class Orders(BaseModel):
    """public.orders"""

    orderNumber: int = Field(alias="orderNumber")
    orderDate: datetime = Field(alias="orderDate")
    requiredDate: datetime = Field(alias="requiredDate")
    shippedDate: Optional[datetime] = Field(alias="shippedDate")
    status: str = Field(alias="status")
    comments: Optional[str] = Field(alias="comments")
    customerNumber: int = Field(alias="customerNumber")


class Payments(BaseModel):
    """public.payments"""

    customerNumber: int = Field(alias="customerNumber")
    checkNumber: str = Field(alias="checkNumber")
    paymentDate: datetime = Field(alias="paymentDate")
    amount: Decimal = Field(alias="amount")


class Productlines(BaseModel):
    """public.productlines"""

    productLine: str = Field(alias="productLine")
    textDescription: Optional[str] = Field(alias="textDescription")
    htmlDescription: Optional[str] = Field(alias="htmlDescription")
    image: Optional[bytes] = Field(alias="image")


class Products(BaseModel):
    """public.products"""

    productCode: str = Field(alias="productCode")
    productName: str = Field(alias="productName")
    productLine: str = Field(alias="productLine")
    productScale: str = Field(alias="productScale")
    productVendor: str = Field(alias="productVendor")
    productDescription: str = Field(alias="productDescription")
    quantityInStock: int = Field(alias="quantityInStock")
    buyPrice: Decimal = Field(alias="buyPrice")
    MSRP: Decimal = Field(alias="MSRP")
