# Code generated by dbtools generate. DO NOT EDIT.
# Source target: test-target @ 2026-08-22T04:00:00Z

from __future__ import annotations
from datetime import datetime
from decimal import Decimal
from typing import Optional

from pydantic import BaseModel, Field


class Customers(BaseModel):
    """public.customers"""

    customernumber: int = Field(alias="customernumber")
    customername: str = Field(alias="customername")
    contactlastname: str = Field(alias="contactlastname")
    contactfirstname: str = Field(alias="contactfirstname")
    phone: str = Field(alias="phone")
    addressline1: str = Field(alias="addressline1")
    addressline2: Optional[str] = Field(alias="addressline2")
    city: str = Field(alias="city")
    state: Optional[str] = Field(alias="state")
    postalcode: Optional[str] = Field(alias="postalcode")
    country: str = Field(alias="country")
    salesrepemployeenumber: Optional[int] = Field(alias="salesrepemployeenumber")
    creditlimit: Optional[Decimal] = Field(alias="creditlimit")


class Employees(BaseModel):
    """public.employees"""

    employeenumber: int = Field(alias="employeenumber")
    lastname: str = Field(alias="lastname")
    firstname: str = Field(alias="firstname")
    extension: str = Field(alias="extension")
    email: str = Field(alias="email")
    officecode: str = Field(alias="officecode")
    reportsto: Optional[int] = Field(alias="reportsto")
    jobtitle: str = Field(alias="jobtitle")


class Offices(BaseModel):
    """public.offices"""

    officecode: str = Field(alias="officecode")
    city: str = Field(alias="city")
    phone: str = Field(alias="phone")
    addressline1: str = Field(alias="addressline1")
    addressline2: Optional[str] = Field(alias="addressline2")
    state: Optional[str] = Field(alias="state")
    country: str = Field(alias="country")
    postalcode: str = Field(alias="postalcode")
    territory: str = Field(alias="territory")


class Orderdetails(BaseModel):
    """public.orderdetails"""

    ordernumber: int = Field(alias="ordernumber")
    productcode: str = Field(alias="productcode")
    quantityordered: int = Field(alias="quantityordered")
    priceeach: Decimal = Field(alias="priceeach")
    orderlinenumber: int = Field(alias="orderlinenumber")


class Orders(BaseModel):
    """public.orders"""

    ordernumber: int = Field(alias="ordernumber")
    orderdate: datetime = Field(alias="orderdate")
    requireddate: datetime = Field(alias="requireddate")
    shippeddate: Optional[datetime] = Field(alias="shippeddate")
    status: str = Field(alias="status")
    comments: Optional[str] = Field(alias="comments")
    customernumber: int = Field(alias="customernumber")


class Payments(BaseModel):
    """public.payments"""

    customernumber: int = Field(alias="customernumber")
    checknumber: str = Field(alias="checknumber")
    paymentdate: datetime = Field(alias="paymentdate")
    amount: Decimal = Field(alias="amount")


class Productlines(BaseModel):
    """public.productlines"""

    productline: str = Field(alias="productline")
    textdescription: Optional[str] = Field(alias="textdescription")
    htmldescription: Optional[str] = Field(alias="htmldescription")
    image: Optional[bytes] = Field(alias="image")


class Products(BaseModel):
    """public.products"""

    productcode: str = Field(alias="productcode")
    productname: str = Field(alias="productname")
    productline: str = Field(alias="productline")
    productscale: str = Field(alias="productscale")
    productvendor: str = Field(alias="productvendor")
    productdescription: str = Field(alias="productdescription")
    quantityinstock: int = Field(alias="quantityinstock")
    buyprice: Decimal = Field(alias="buyprice")
    msrp: Decimal = Field(alias="msrp")
