// Code generated by dbtools generate. DO NOT EDIT.
// Source target: test-target @ 2026-08-22T04:00:00Z
import { z } from "zod";
export interface Customers {
  customernumber: number;
  customername: string;
  contactlastname: string;
  contactfirstname: string;
  phone: string;
  addressline1: string;
  addressline2?: string | null;
  city: string;
  state?: string | null;
  postalcode?: string | null;
  country: string;
  salesrepemployeenumber?: number | null;
  creditlimit?: number | null;
}
export const CustomersSchema = z.object({
  customernumber: z.number(),
  customername: z.string(),
  contactlastname: z.string(),
  contactfirstname: z.string(),
  phone: z.string(),
  addressline1: z.string(),
  addressline2: z.string().nullish(),
  city: z.string(),
  state: z.string().nullish(),
  postalcode: z.string().nullish(),
  country: z.string(),
  salesrepemployeenumber: z.number().nullish(),
  creditlimit: z.number().nullish(),
});
export interface Employees {
  employeenumber: number;
  lastname: string;
  firstname: string;
  extension: string;
  email: string;
  officecode: string;
  reportsto?: number | null;
  jobtitle: string;
}
export const EmployeesSchema = z.object({
  employeenumber: z.number(),
  lastname: z.string(),
  firstname: z.string(),
  extension: z.string(),
  email: z.string(),
  officecode: z.string(),
  reportsto: z.number().nullish(),
  jobtitle: z.string(),
});
export interface Offices {
  officecode: string;
  city: string;
  phone: string;
  addressline1: string;
  addressline2?: string | null;
  state?: string | null;
  country: string;
  postalcode: string;
  territory: string;
}
export const OfficesSchema = z.object({
  officecode: z.string(),
  city: z.string(),
  phone: z.string(),
  addressline1: z.string(),
  addressline2: z.string().nullish(),
  state: z.string().nullish(),
  country: z.string(),
  postalcode: z.string(),
  territory: z.string(),
});
export interface Orderdetails {
  ordernumber: number;
  productcode: string;
  quantityordered: number;
  priceeach: number;
  orderlinenumber: number;
}
export const OrderdetailsSchema = z.object({
  ordernumber: z.number(),
  productcode: z.string(),
  quantityordered: z.number(),
  priceeach: z.number(),
  orderlinenumber: z.number(),
});
export interface Orders {
  ordernumber: number;
  orderdate: string;
  requireddate: string;
  shippeddate?: string | null;
  status: string;
  comments?: string | null;
  customernumber: number;
}
export const OrdersSchema = z.object({
  ordernumber: z.number(),
  orderdate: z.string(),
  requireddate: z.string(),
  shippeddate: z.string().nullish(),
  status: z.string(),
  comments: z.string().nullish(),
  customernumber: z.number(),
});
export interface Payments {
  customernumber: number;
  checknumber: string;
  paymentdate: string;
  amount: number;
}
export const PaymentsSchema = z.object({
  customernumber: z.number(),
  checknumber: z.string(),
  paymentdate: z.string(),
  amount: z.number(),
});
export interface Productlines {
  productline: string;
  textdescription?: string | null;
  htmldescription?: string | null;
  image?: any | null;
}
export const ProductlinesSchema = z.object({
  productline: z.string(),
  textdescription: z.string().nullish(),
  htmldescription: z.string().nullish(),
  image: z.any().nullish(),
});
export interface Products {
  productcode: string;
  productname: string;
  productline: string;
  productscale: string;
  productvendor: string;
  productdescription: string;
  quantityinstock: number;
  buyprice: number;
  msrp: number;
}
export const ProductsSchema = z.object({
  productcode: z.string(),
  productname: z.string(),
  productline: z.string(),
  productscale: z.string(),
  productvendor: z.string(),
  productdescription: z.string(),
  quantityinstock: z.number(),
  buyprice: z.number(),
  msrp: z.number(),
});
