// Code generated by dbtools generate. DO NOT EDIT.
// Source target: test-target @ 2026-08-22T04:00:00Z
import { z } from "zod";
export interface Customers {
  customerNumber: number;
  customerName: string;
  contactLastName: string;
  contactFirstName: string;
  phone: string;
  addressLine1: string;
  addressLine2?: string | null;
  city: string;
  state?: string | null;
  postalCode?: string | null;
  country: string;
  salesRepEmployeeNumber?: number | null;
  creditLimit?: number | null;
}
export const CustomersSchema = z.object({
  customerNumber: z.number(),
  customerName: z.string(),
  contactLastName: z.string(),
  contactFirstName: z.string(),
  phone: z.string(),
  addressLine1: z.string(),
  addressLine2: z.string().nullish(),
  city: z.string(),
  state: z.string().nullish(),
  postalCode: z.string().nullish(),
  country: z.string(),
  salesRepEmployeeNumber: z.number().nullish(),
  creditLimit: z.number().nullish(),
});
export interface Employees {
  employeeNumber: number;
  lastName: string;
  firstName: string;
  extension: string;
  email: string;
  officeCode: string;
  reportsTo?: number | null;
  jobTitle: string;
}
export const EmployeesSchema = z.object({
  employeeNumber: z.number(),
  lastName: z.string(),
  firstName: z.string(),
  extension: z.string(),
  email: z.string(),
  officeCode: z.string(),
  reportsTo: z.number().nullish(),
  jobTitle: z.string(),
});
export interface Offices {
  officeCode: string;
  city: string;
  phone: string;
  addressLine1: string;
  addressLine2?: string | null;
  state?: string | null;
  country: string;
  postalCode: string;
  territory: string;
}
export const OfficesSchema = z.object({
  officeCode: z.string(),
  city: z.string(),
  phone: z.string(),
  addressLine1: z.string(),
  addressLine2: z.string().nullish(),
  state: z.string().nullish(),
  country: z.string(),
  postalCode: z.string(),
  territory: z.string(),
});
export interface Orderdetails {
  orderNumber: number;
  productCode: string;
  quantityOrdered: number;
  priceEach: number;
  orderLineNumber: number;
}
export const OrderdetailsSchema = z.object({
  orderNumber: z.number(),
  productCode: z.string(),
  quantityOrdered: z.number(),
  priceEach: z.number(),
  orderLineNumber: z.number(),
});
export interface Orders {
  orderNumber: number;
  orderDate: string;
  requiredDate: string;
  shippedDate?: string | null;
  status: string;
  comments?: string | null;
  customerNumber: number;
}
export const OrdersSchema = z.object({
  orderNumber: z.number(),
  orderDate: z.string(),
  requiredDate: z.string(),
  shippedDate: z.string().nullish(),
  status: z.string(),
  comments: z.string().nullish(),
  customerNumber: z.number(),
});
export interface Payments {
  customerNumber: number;
  checkNumber: string;
  paymentDate: string;
  amount: number;
}
export const PaymentsSchema = z.object({
  customerNumber: z.number(),
  checkNumber: z.string(),
  paymentDate: z.string(),
  amount: z.number(),
});
export interface Productlines {
  productLine: string;
  textDescription?: string | null;
  htmlDescription?: string | null;
  image?: any | null;
}
export const ProductlinesSchema = z.object({
  productLine: z.string(),
  textDescription: z.string().nullish(),
  htmlDescription: z.string().nullish(),
  image: z.any().nullish(),
});
export interface Products {
  productCode: string;
  productName: string;
  productLine: string;
  productScale: string;
  productVendor: string;
  productDescription: string;
  quantityInStock: number;
  buyPrice: number;
  MSRP: number;
}
export const ProductsSchema = z.object({
  productCode: z.string(),
  productName: z.string(),
  productLine: z.string(),
  productScale: z.string(),
  productVendor: z.string(),
  productDescription: z.string(),
  quantityInStock: z.number(),
  buyPrice: z.number(),
  MSRP: z.number(),
});
