package generate

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
	"time"
)

// ToPascalCase converts a snake_case name into PascalCase, e.g. "user_account" -> "UserAccount".
// The result is guaranteed to be a valid Python/Go identifier: characters
// outside [A-Za-z0-9_] are dropped (so "trade-log" -> "TradeLog"), and a
// leading digit is prefixed with an underscore (so "2fa_codes" ->
// "_2faCodes"). Callers that need to round-trip the original column name
// must keep it separately — generate does this via Field(alias=...).
func ToPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' || r == ' ' || r == '.' })
	var res []string
	for _, part := range parts {
		if part == "" {
			continue
		}
		lower := strings.ToLower(part)
		first := strings.ToUpper(lower[:1])
		res = append(res, first+lower[1:])
	}
	joined := strings.Join(res, "")
	if joined == "" {
		return "Empty"
	}
	if joined[0] >= '0' && joined[0] <= '9' {
		return "_" + joined
	}
	return joined
}

// ResolveClassNames assigns class names to tables, disambiguating collisions by prefixing the schema name.
// Returns an error if two tables still resolve to the same class name after disambiguation.
func ResolveClassNames(tables []TableSchema) ([]TableSchema, error) {
	counts := make(map[string]int)
	pascalNames := make([]string, len(tables))

	for i, t := range tables {
		name := ToPascalCase(t.Name)
		pascalNames[i] = name
		counts[name]++
	}

	result := make([]TableSchema, len(tables))
	finalCounts := make(map[string]string) // class name -> first schema.table that claimed it
	for i, t := range tables {
		name := pascalNames[i]
		if counts[name] > 1 {
			name = ToPascalCase(t.Schema) + name
		}
		t.ClassName = name
		result[i] = t

		fullKey := fmt.Sprintf("%s.%s", t.Schema, t.Name)
		if owner, exists := finalCounts[name]; exists {
			return nil, fmt.Errorf("class name %q collides between %q and %q; rename one of the tables or extend disambiguation", name, owner, fullKey)
		}
		finalCounts[name] = fullKey
	}
	return result, nil
}

// pythonKeywords are reserved words that cannot be used as Python identifiers.
var pythonKeywords = map[string]bool{
	"False": true, "None": true, "True": true, "and": true, "as": true,
	"assert": true, "async": true, "await": true, "break": true, "class": true,
	"continue": true, "def": true, "del": true, "elif": true, "else": true,
	"except": true, "finally": true, "for": true, "from": true, "global": true,
	"if": true, "import": true, "in": true, "is": true, "lambda": true,
	"nonlocal": true, "not": true, "or": true, "pass": true, "raise": true,
	"return": true, "try": true, "while": true, "with": true, "yield": true,
}

// SanitizeFieldName makes a column name a valid Python identifier while
// keeping it readable:
//   - Python keywords get a trailing underscore (idiomatic: `class` -> `class_`)
//   - characters outside [A-Za-z0-9_] are dropped (`user id` -> `userid`)
//   - a leading digit is prefixed with an underscore (`2fa` -> `_2fa`)
//
// Exported so other engines' introspectors build columns the same way.
// The original column name is kept for the generated Field(alias=...),
// so the mapping still round-trips (see Render).
func SanitizeFieldName(name string) string {
	if pythonKeywords[name] {
		return name + "_"
	}
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		}
	}
	out := b.String()
	if out == "" {
		return "_"
	}
	if out[0] >= '0' && out[0] <= '9' {
		return "_" + out
	}
	return out
}

type RenderData struct {
	Target        string
	Timestamp     string
	Version       string
	NeedDecimal   bool
	NeedDatetime  bool
	NeedTime      bool
	NeedUUID      bool
	NeedAny       bool
	NeedOptional  bool
	TypingImports string
	Tables        []TableSchema
}

const pydanticTemplate = `# Code generated by dbtools generate. DO NOT EDIT.
# Source target: {{ .Target }} @ {{ .Timestamp }}

from __future__ import annotations

{{- if or .NeedDatetime .NeedTime }}
from datetime import {{ if .NeedDatetime }}datetime{{ end }}{{ if and .NeedDatetime .NeedTime }}, {{ end }}{{ if .NeedTime }}time{{ end }}
{{- end }}
{{- if .NeedDecimal }}
from decimal import Decimal
{{- end }}
{{- if .TypingImports }}
from typing import {{ .TypingImports }}
{{- end }}
{{- if .NeedUUID }}
from uuid import UUID
{{- end }}

from pydantic import BaseModel, Field


{{ range $i, $t := .Tables }}{{ if $i }}

{{ end }}class {{ $t.ClassName }}(BaseModel):
    """{{ $t.Schema }}.{{ $t.Name }}"""
{{ range $t.Columns }}
    {{ .PyName }}: {{ if .IsNullable }}Optional[{{ .PythonType }}] = Field(alias={{ printf "%q" .Name }}){{ else }}{{ .PythonType }} = Field(alias={{ printf "%q" .Name }}){{ end }}{{ end }}
{{ end }}`

// typingImports builds the comma-joined `from typing import ...` payload,
// e.g. "Any, Optional" — done in Go so a trailing comma can never be
// emitted (a bare `from typing import Any, ` is a SyntaxError; see C6).
func typingImports(needAny, needOptional bool) string {
	var names []string
	if needAny {
		names = append(names, "Any")
	}
	if needOptional {
		names = append(names, "Optional")
	}
	return strings.Join(names, ", ")
}

// Render generates the Python pydantic BaseModel code for the given tables.
func Render(tables []TableSchema, target string) (string, error) {
	resolvedTables, err := ResolveClassNames(tables)
	if err != nil {
		return "", err
	}

	data := RenderData{
		Target:    target,
		Timestamp: time.Now().UTC().Format(time.RFC3339),
		Version:   "1.0.0",
		Tables:    resolvedTables,
	}

	for _, t := range resolvedTables {
		for _, c := range t.Columns {
			if c.IsNullable {
				data.NeedOptional = true
			}
			switch c.PythonType {
			case "Decimal":
				data.NeedDecimal = true
			case "datetime":
				data.NeedDatetime = true
			case "time":
				data.NeedTime = true
			case "UUID":
				data.NeedUUID = true
			case "Any":
				data.NeedAny = true
			}
		}
	}
	data.TypingImports = typingImports(data.NeedAny, data.NeedOptional)

	tmpl, err := template.New("pydantic").Parse(pydanticTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing pydantic template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing pydantic template: %w", err)
	}

	return buf.String(), nil
}
