package generate

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
	"time"
)

// ToPascalCase converts a snake_case name into PascalCase, e.g. "user_account" -> "UserAccount".
func ToPascalCase(s string) string {
	parts := strings.Split(s, "_")
	var res []string
	for _, part := range parts {
		if part == "" {
			continue
		}
		res = append(res, strings.Title(strings.ToLower(part)))
	}
	return strings.Join(res, "")
}

// ResolveClassNames assigns class names to tables, disambiguating collisions by prefixing the schema name.
// Returns an error if two tables still resolve to the same class name after disambiguation.
func ResolveClassNames(tables []TableSchema) ([]TableSchema, error) {
	counts := make(map[string]int)
	pascalNames := make([]string, len(tables))

	for i, t := range tables {
		name := ToPascalCase(t.Name)
		pascalNames[i] = name
		counts[name]++
	}

	result := make([]TableSchema, len(tables))
	finalCounts := make(map[string]string) // class name -> first schema.table that claimed it
	for i, t := range tables {
		name := pascalNames[i]
		if counts[name] > 1 {
			name = ToPascalCase(t.Schema) + name
		}
		t.ClassName = name
		result[i] = t

		fullKey := fmt.Sprintf("%s.%s", t.Schema, t.Name)
		if owner, exists := finalCounts[name]; exists {
			return nil, fmt.Errorf("class name %q collides between %q and %q; rename one of the tables or extend disambiguation", name, owner, fullKey)
		}
		finalCounts[name] = fullKey
	}
	return result, nil
}

// pythonKeywords are reserved words that cannot be used as Python identifiers.
var pythonKeywords = map[string]bool{
	"False": true, "None": true, "True": true, "and": true, "as": true,
	"assert": true, "async": true, "await": true, "break": true, "class": true,
	"continue": true, "def": true, "del": true, "elif": true, "else": true,
	"except": true, "finally": true, "for": true, "from": true, "global": true,
	"if": true, "import": true, "in": true, "is": true, "lambda": true,
	"nonlocal": true, "not": true, "or": true, "pass": true, "raise": true,
	"return": true, "try": true, "while": true, "with": true, "yield": true,
}

// SanitizeFieldName appends a trailing underscore to Python-keyword column
// names, matching the idiomatic Python convention (e.g. `class` -> `class_`).
// Exported so other engines' introspectors build columns the same way.
func SanitizeFieldName(name string) string {
	if pythonKeywords[name] {
		return name + "_"
	}
	return name
}

type RenderData struct {
	Target       string
	Timestamp    string
	Version      string
	NeedDecimal  bool
	NeedDatetime bool
	NeedTime     bool
	NeedUUID     bool
	NeedAny      bool
	NeedOptional bool
	Tables       []TableSchema
}

const pydanticTemplate = `# Code generated by dbtools generate. DO NOT EDIT.
# Source target: {{ .Target }} @ {{ .Timestamp }}

from __future__ import annotations

{{- if or .NeedDatetime .NeedTime }}
from datetime import {{ if .NeedDatetime }}datetime{{ end }}{{ if and .NeedDatetime .NeedTime }}, {{ end }}{{ if .NeedTime }}time{{ end }}
{{- end }}
{{- if .NeedDecimal }}
from decimal import Decimal
{{- end }}
{{- if or .NeedAny .NeedOptional }}
from typing import {{ if .NeedAny }}Any, {{ end }}{{ if .NeedOptional }}Optional{{ end }}
{{- end }}
{{- if .NeedUUID }}
from uuid import UUID
{{- end }}

from pydantic import BaseModel


{{ range $i, $t := .Tables }}{{ if $i }}

{{ end }}class {{ $t.ClassName }}(BaseModel):
    """{{ $t.Schema }}.{{ $t.Name }}"""
{{ range $t.Columns }}
    {{ .PyName }}: {{ if .IsNullable }}Optional[{{ .PythonType }}] = None{{ else }}{{ .PythonType }}{{ end }}{{ end }}
{{ end }}`

// Render generates the Python pydantic BaseModel code for the given tables.
func Render(tables []TableSchema, target string) (string, error) {
	resolvedTables, err := ResolveClassNames(tables)
	if err != nil {
		return "", err
	}

	data := RenderData{
		Target:    target,
		Timestamp: time.Now().UTC().Format(time.RFC3339),
		Version:   "1.0.0",
		Tables:    resolvedTables,
	}

	for _, t := range resolvedTables {
		for _, c := range t.Columns {
			if c.IsNullable {
				data.NeedOptional = true
			}
			switch c.PythonType {
			case "Decimal":
				data.NeedDecimal = true
			case "datetime":
				data.NeedDatetime = true
			case "time":
				data.NeedTime = true
			case "UUID":
				data.NeedUUID = true
			case "Any":
				data.NeedAny = true
			}
		}
	}

	tmpl, err := template.New("pydantic").Parse(pydanticTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing pydantic template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing pydantic template: %w", err)
	}

	return buf.String(), nil
}
